name: tech_lancer_teacher
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  video_thumbnail: ^0.5.3
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  cached_network_image:
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  network_info_plus: ^4.1.0
  get_ip_address: ^0.0.6
  svg_flutter: ^0.0.1
  line_icons: ^2.0.3
  awesome_snackbar_content: 
  image_picker: 
  permission_handler: ^11.0.1
  photo_manager: ^2.7.2
  fluttertoast:
  path_provider:
  video_player: any
  file_picker:
  animated_text_kit: ^4.2.2
  chewie: 
  socket_io_client: ^2.0.3+1
  connectivity_plus: ^5.0.2
  photo_view: ^0.14.0
  easy_pdf_viewer: ^1.0.7
  expandable: ^5.0.1
  http:


dev_dependencies: 
  flutter_lints: ^2.0.0
  # get_cli: ^1.8.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf

